/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wss.viwer;

import br.com.wss.dao.BensDao;
import br.com.wss.dao.FornecedorDao;
import br.com.wss.dao.GrupoDao;
import br.com.wss.modelo.Bens;
import br.com.wss.tabelas.Tabela;
import br.com.wss.tabelas.TabelaBens;
import br.com.wss.utilidades.ClassEvents;
import br.com.wss.utilidades.ClassUtils;
import br.com.wss.utilidades.FocusLost;
import br.com.wss.utilidades.FormatDouble;
import br.com.wss.utilidades.NumeroMaximoCaracters;
import br.com.wss.utilidades.SomenteNumero;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author WILLIAM
 */
public final class FrmBens extends javax.swing.JInternalFrame {

    ArrayList<Bens> dados;

    GrupoDao grupoDao = new GrupoDao();
    FornecedorDao fornecedorDao = new FornecedorDao();
    BensDao bensDao = new BensDao();
    Bens bensTemp = new Bens();
    int modificador = 1;

    /**
     * Creates new form FrmBens
     */
    public FrmBens() {
        init();
    }

    public void init() {
        initComponents();
        preencherComboGrupo();
        preencherComboVoltagen();
        preencherComboStatus();
        preencherComboFornecedor();
        preencherTabela();
        enventFocus();

        this.setLocation(260, 0);
        this.setSize(1100, 660);
        validaCampos();

        jTextFieldIdbens.setVisible(false);
        jPanelSecundario.setVisible(false);
        jPanelBens.setVisible(false);
        jButtonExcluir.setEnabled(false);

        jTextFieldDepreciacaoDiaria.setEditable(false);
        jTextFieldValorAtual.setEditable(false);
        jTextFieldTempoUso.setEditable(false);
        jTextFieldTempoUsoPorcento.setEditable(false);

        jDateChooserDataCompra.setEnabled(false);
        jDateChooserDataCompra.getCalendarButton().setEnabled(true);
        jDateChooserDataCompra.setDate(new Date());
        jDateChooserFinalGarantia.setEnabled(false);
        jDateChooserFinalGarantia.getCalendarButton().setVisible(false);
        jDateChooserFinalVidaUtil.setEnabled(false);
        jDateChooserFinalVidaUtil.getCalendarButton().setVisible(false);
        jDateChooserFinalGarantiaManutencao.setEnabled(false);
        jDateChooserInicioGarantiaManutencao.setEnabled(false);
        jDateChooserFinalGarantiaManutencao.getCalendarButton().setEnabled(false);
        jDateChooserInicioGarantiaManutencao.getCalendarButton().setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBens = new javax.swing.JPanel();
        jTextFieldNomeBen = new javax.swing.JTextField();
        jTextFieldNumeroControle = new javax.swing.JTextField();
        jTextFieldLocal = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldNumeroSerie = new javax.swing.JTextField();
        jComboBoxGrupo = new javax.swing.JComboBox();
        jComboBoxVoltagen = new javax.swing.JComboBox();
        jComboBoxFornecedor = new javax.swing.JComboBox();
        jComboBoxStatus = new javax.swing.JComboBox();
        jTextFieldNotalFiscal = new javax.swing.JTextField();
        jDateChooserDataCompra = new com.toedter.calendar.JDateChooser();
        jTextFieldValorCompra = new javax.swing.JTextField();
        jTextFieldGarantia = new javax.swing.JTextField();
        jTextFieldVidaUtil = new javax.swing.JTextField();
        jLabelValorCompra = new javax.swing.JLabel();
        jLabelDataCompra = new javax.swing.JLabel();
        jLabelGrupo = new javax.swing.JLabel();
        jLabelVoltagem = new javax.swing.JLabel();
        jLabelNumeroSerie = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelObservacoes = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNomeBens = new javax.swing.JLabel();
        jTextFieldIdbens = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldObservaçoes = new javax.swing.JTextArea();
        jLabelFornecedor = new javax.swing.JLabel();
        jLabelVidaUtil = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jLabelGarantia = new javax.swing.JLabel();
        jLabelNumeroControle = new javax.swing.JLabel();
        jLabelNotaFiscal = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanelSecundario = new javax.swing.JPanel();
        jLabelFinalGarantia = new javax.swing.JLabel();
        jLabelFinalVidaUtil = new javax.swing.JLabel();
        jLabeltempoUso = new javax.swing.JLabel();
        jTextFieldTempoUso = new javax.swing.JTextField();
        jLabelDescricaoDepreciacaoDiaria = new javax.swing.JLabel();
        jTextFieldDepreciacaoDiaria = new javax.swing.JTextField();
        jTextFieldValorAtual = new javax.swing.JTextField();
        jLabelValorAtual = new javax.swing.JLabel();
        jLabelTempoUsoPorcento = new javax.swing.JLabel();
        jTextFieldTempoUsoPorcento = new javax.swing.JTextField();
        jDateChooserFinalGarantia = new com.toedter.calendar.JDateChooser();
        jDateChooserFinalVidaUtil = new com.toedter.calendar.JDateChooser();
        jLabelGarantiaManutencao = new javax.swing.JLabel();
        jLabelInicioGarantiaManutencao = new javax.swing.JLabel();
        jLabelFimGarantiaManutencao = new javax.swing.JLabel();
        jDateChooserInicioGarantiaManutencao = new com.toedter.calendar.JDateChooser();
        jDateChooserFinalGarantiaManutencao = new com.toedter.calendar.JDateChooser();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBens = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Bens");

        jPanelBens.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));
        jPanelBens.setLayout(null);

        jTextFieldNomeBen.setText("jTextField1");
        jTextFieldNomeBen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeBenFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldNomeBen);
        jTextFieldNomeBen.setBounds(144, 29, 190, 26);
        jTextFieldNomeBen.getAccessibleContext().setAccessibleParent(this);

        jTextFieldNumeroControle.setText("jTextField1");
        jTextFieldNumeroControle.setSelectionEnd(12);
        jTextFieldNumeroControle.setSelectionStart(12);
        jTextFieldNumeroControle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroControleFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldNumeroControle);
        jTextFieldNumeroControle.setBounds(144, 59, 190, 26);
        jTextFieldNumeroControle.getAccessibleContext().setAccessibleParent(this);

        jTextFieldLocal.setText("jTextField8");
        jTextFieldLocal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLocalFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldLocal);
        jTextFieldLocal.setBounds(144, 89, 190, 26);

        jTextFieldModelo.setText("jTextField1");
        jTextFieldModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldModeloFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldModelo);
        jTextFieldModelo.setBounds(144, 119, 190, 26);

        jTextFieldNumeroSerie.setText("jTextField1");
        jTextFieldNumeroSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroSerieFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldNumeroSerie);
        jTextFieldNumeroSerie.setBounds(144, 149, 190, 26);

        jComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxGrupoFocusLost(evt);
            }
        });
        jPanelBens.add(jComboBoxGrupo);
        jComboBoxGrupo.setBounds(144, 179, 190, 26);

        jComboBoxVoltagen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        jComboBoxVoltagen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxVoltagenFocusLost(evt);
            }
        });
        jPanelBens.add(jComboBoxVoltagen);
        jComboBoxVoltagen.setBounds(144, 211, 190, 26);

        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        jComboBoxFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxFornecedorFocusLost(evt);
            }
        });
        jPanelBens.add(jComboBoxFornecedor);
        jComboBoxFornecedor.setBounds(144, 240, 190, 26);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxStatusFocusLost(evt);
            }
        });
        jPanelBens.add(jComboBoxStatus);
        jComboBoxStatus.setBounds(482, 29, 190, 26);

        jTextFieldNotalFiscal.setText("jTextField1");
        jTextFieldNotalFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNotalFiscalFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldNotalFiscal);
        jTextFieldNotalFiscal.setBounds(482, 59, 190, 26);
        jPanelBens.add(jDateChooserDataCompra);
        jDateChooserDataCompra.setBounds(482, 89, 190, 26);

        jTextFieldValorCompra.setText("jTextField1");
        jTextFieldValorCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorCompraFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldValorCompra);
        jTextFieldValorCompra.setBounds(482, 119, 190, 26);

        jTextFieldGarantia.setText("jTextField1");
        jTextFieldGarantia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldGarantiaFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldGarantia);
        jTextFieldGarantia.setBounds(482, 149, 190, 26);

        jTextFieldVidaUtil.setText("jTextField1");
        jTextFieldVidaUtil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldVidaUtilFocusLost(evt);
            }
        });
        jPanelBens.add(jTextFieldVidaUtil);
        jTextFieldVidaUtil.setBounds(482, 179, 190, 26);

        jLabelValorCompra.setText("Valor de Compra:");
        jPanelBens.add(jLabelValorCompra);
        jLabelValorCompra.setBounds(362, 119, 110, 20);

        jLabelDataCompra.setText("Data da Compra:");
        jPanelBens.add(jLabelDataCompra);
        jLabelDataCompra.setBounds(362, 89, 110, 20);

        jLabelGrupo.setText("Grupo:");
        jPanelBens.add(jLabelGrupo);
        jLabelGrupo.setBounds(19, 179, 110, 20);

        jLabelVoltagem.setText("Voltagem:");
        jPanelBens.add(jLabelVoltagem);
        jLabelVoltagem.setBounds(19, 211, 110, 20);

        jLabelNumeroSerie.setText("N° Série:");
        jLabelNumeroSerie.setToolTipText("");
        jPanelBens.add(jLabelNumeroSerie);
        jLabelNumeroSerie.setBounds(19, 149, 110, 20);

        jLabelModelo.setText("Modelo:");
        jPanelBens.add(jLabelModelo);
        jLabelModelo.setBounds(19, 119, 110, 20);

        jLabelStatus.setText("Status:");
        jPanelBens.add(jLabelStatus);
        jLabelStatus.setBounds(362, 29, 110, 20);

        jLabelObservacoes.setText("Observações:");
        jPanelBens.add(jLabelObservacoes);
        jLabelObservacoes.setBounds(492, 211, 100, 20);

        jButtonSalvar.setText("Variavel");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });
        jPanelBens.add(jButtonSalvar);
        jButtonSalvar.setBounds(144, 287, 80, 26);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelBens.add(jButtonCancelar);
        jButtonCancelar.setBounds(254, 287, 80, 26);

        jLabelNomeBens.setText("Equipamento:");
        jPanelBens.add(jLabelNomeBens);
        jLabelNomeBens.setBounds(19, 29, 110, 20);

        jTextFieldIdbens.setText("IdBENS");
        jPanelBens.add(jTextFieldIdbens);
        jTextFieldIdbens.setBounds(19, 290, 41, 20);

        jTextFieldObservaçoes.setColumns(20);
        jTextFieldObservaçoes.setRows(5);
        jTextFieldObservaçoes.setText("\n\n\n\n\n\n\n");
        jScrollPane1.setViewportView(jTextFieldObservaçoes);

        jPanelBens.add(jScrollPane1);
        jScrollPane1.setBounds(352, 243, 320, 70);

        jLabelFornecedor.setText("Fornecedor:");
        jPanelBens.add(jLabelFornecedor);
        jLabelFornecedor.setBounds(16, 246, 110, 20);

        jLabelVidaUtil.setText("Vida Util Estimada:");
        jPanelBens.add(jLabelVidaUtil);
        jLabelVidaUtil.setBounds(362, 179, 110, 20);

        jLabelLocal.setText("Local:");
        jPanelBens.add(jLabelLocal);
        jLabelLocal.setBounds(19, 89, 110, 20);

        jLabelGarantia.setText("Garantia em Dias:");
        jPanelBens.add(jLabelGarantia);
        jLabelGarantia.setBounds(362, 149, 110, 20);

        jLabelNumeroControle.setText("N° de controle:");
        jPanelBens.add(jLabelNumeroControle);
        jLabelNumeroControle.setBounds(19, 59, 110, 20);

        jLabelNotaFiscal.setText("Nº Notal Fiscal:");
        jPanelBens.add(jLabelNotaFiscal);
        jLabelNotaFiscal.setBounds(362, 59, 110, 20);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jPanelSecundario.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));
        jPanelSecundario.setLayout(null);

        jLabelFinalGarantia.setText("Fim da Garantia:");
        jPanelSecundario.add(jLabelFinalGarantia);
        jLabelFinalGarantia.setBounds(20, 30, 160, 20);

        jLabelFinalVidaUtil.setText("Termino Vida Util:");
        jPanelSecundario.add(jLabelFinalVidaUtil);
        jLabelFinalVidaUtil.setBounds(20, 60, 160, 20);

        jLabeltempoUso.setText("Tempo de Uso em Dias:");
        jPanelSecundario.add(jLabeltempoUso);
        jLabeltempoUso.setBounds(20, 90, 160, 20);

        jTextFieldTempoUso.setText("jTextField1");
        jPanelSecundario.add(jTextFieldTempoUso);
        jTextFieldTempoUso.setBounds(210, 90, 150, 26);

        jLabelDescricaoDepreciacaoDiaria.setText("Depreciação Diaria:");
        jPanelSecundario.add(jLabelDescricaoDepreciacaoDiaria);
        jLabelDescricaoDepreciacaoDiaria.setBounds(20, 120, 160, 20);

        jTextFieldDepreciacaoDiaria.setText("jTextField1");
        jPanelSecundario.add(jTextFieldDepreciacaoDiaria);
        jTextFieldDepreciacaoDiaria.setBounds(210, 120, 150, 26);

        jTextFieldValorAtual.setText("jTextField1");
        jPanelSecundario.add(jTextFieldValorAtual);
        jTextFieldValorAtual.setBounds(210, 150, 150, 26);

        jLabelValorAtual.setText("Valor Atual:");
        jPanelSecundario.add(jLabelValorAtual);
        jLabelValorAtual.setBounds(20, 150, 160, 20);

        jLabelTempoUsoPorcento.setText("Tempo de Uso %:");
        jPanelSecundario.add(jLabelTempoUsoPorcento);
        jLabelTempoUsoPorcento.setBounds(20, 180, 160, 20);

        jTextFieldTempoUsoPorcento.setText("jTextField1");
        jPanelSecundario.add(jTextFieldTempoUsoPorcento);
        jTextFieldTempoUsoPorcento.setBounds(210, 180, 150, 26);
        jPanelSecundario.add(jDateChooserFinalGarantia);
        jDateChooserFinalGarantia.setBounds(210, 30, 150, 26);
        jPanelSecundario.add(jDateChooserFinalVidaUtil);
        jDateChooserFinalVidaUtil.setBounds(210, 60, 150, 26);

        jLabelGarantiaManutencao.setText("Garantia Manutenção");
        jPanelSecundario.add(jLabelGarantiaManutencao);
        jLabelGarantiaManutencao.setBounds(130, 230, 120, 20);

        jLabelInicioGarantiaManutencao.setText("Inicio Garantia Manutenção:");
        jPanelSecundario.add(jLabelInicioGarantiaManutencao);
        jLabelInicioGarantiaManutencao.setBounds(20, 260, 160, 20);

        jLabelFimGarantiaManutencao.setText("Fim Garantia Manutenção:");
        jPanelSecundario.add(jLabelFimGarantiaManutencao);
        jLabelFimGarantiaManutencao.setBounds(20, 290, 160, 20);
        jPanelSecundario.add(jDateChooserInicioGarantiaManutencao);
        jDateChooserInicioGarantiaManutencao.setBounds(210, 260, 150, 26);
        jPanelSecundario.add(jDateChooserFinalGarantiaManutencao);
        jDateChooserFinalGarantiaManutencao.setBounds(210, 290, 150, 26);

        jTableBens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBensMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBens);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBens, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovo)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNovo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBens, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        if (modificador == 1) {
            jPanelBens.setVisible(true);
            jButtonExcluir.setEnabled(false);
            jButtonNovo.setEnabled(false);
            limparCampos();
            jButtonSalvar.setText("Salvar");
        } else {
            modificador = 1;
            jPanelBens.setVisible(true);
            jButtonExcluir.setEnabled(false);
            jButtonNovo.setEnabled(false);
            limparCampos();
            jButtonSalvar.setText("Salvar");
        }
        jTextFieldNomeBen.requestFocus();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (modificador == 1) {
            jButtonSalvar.setText("Salvar");
            cadastrarBens();
        } else if (modificador == 2) {
            jButtonSalvar.setText("Editar");
            editarBens();
        } else {

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jPanelBens.setVisible(false);
        jPanelSecundario.setVisible(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        limparCampos();
        modificador = 1;

        modificadorCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableBensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBensMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                itensSelecionados();
            } catch (ParseException ex) {
                Logger.getLogger(FrmBens.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FrmBens.class.getName()).log(Level.SEVERE, null, ex);
            }
            jPanelSecundario.setVisible(true);
            jPanelBens.setVisible(true);
            jButtonNovo.setEnabled(false);
            jButtonExcluir.setEnabled(true);
            modificador = 2;
            jButtonSalvar.setText("Editar");
        }
    }//GEN-LAST:event_jTableBensMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        deletarBens();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (modificador == 1) {
                jButtonSalvar.setText("Salvar");
                cadastrarBens();
            } else if (modificador == 2) {
                jButtonSalvar.setText("Editar");
                editarBens();
            } else {

            }
        }
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jTextFieldNomeBenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeBenFocusLost
        ClassEvents.focusLostTextField(jLabelNomeBens, jTextFieldNomeBen);
    }//GEN-LAST:event_jTextFieldNomeBenFocusLost

    private void jTextFieldNumeroControleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroControleFocusLost
        ClassEvents.focusLostTextField(jLabelNumeroControle, jTextFieldNumeroControle);
    }//GEN-LAST:event_jTextFieldNumeroControleFocusLost

    private void jTextFieldLocalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLocalFocusLost
        ClassEvents.focusLostTextField(jLabelLocal, jTextFieldLocal);
    }//GEN-LAST:event_jTextFieldLocalFocusLost

    private void jTextFieldModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldModeloFocusLost
       ClassEvents.focusLostTextField(jLabelModelo,jTextFieldModelo);
    }//GEN-LAST:event_jTextFieldModeloFocusLost

    private void jTextFieldNumeroSerieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroSerieFocusLost
        ClassEvents.focusLostTextField(jLabelNumeroSerie, jTextFieldNumeroSerie);
    }//GEN-LAST:event_jTextFieldNumeroSerieFocusLost

    private void jTextFieldNotalFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNotalFiscalFocusLost
        ClassEvents.focusLostTextField(jLabelNotaFiscal, jTextFieldNotalFiscal);
    }//GEN-LAST:event_jTextFieldNotalFiscalFocusLost

    private void jTextFieldValorCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorCompraFocusLost
        ClassEvents.focusLostTextField(jLabelValorCompra, jTextFieldValorCompra);
    }//GEN-LAST:event_jTextFieldValorCompraFocusLost

    private void jTextFieldGarantiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldGarantiaFocusLost
        ClassEvents.focusLostTextField(jLabelGarantia, jTextFieldGarantia);
    }//GEN-LAST:event_jTextFieldGarantiaFocusLost

    private void jTextFieldVidaUtilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldVidaUtilFocusLost
       ClassEvents.focusLostTextField(jLabelVidaUtil, jTextFieldVidaUtil);
    }//GEN-LAST:event_jTextFieldVidaUtilFocusLost

    private void jComboBoxGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxGrupoFocusLost
        ClassEvents.focusLostCombobox(jLabelGrupo, jComboBoxGrupo);
    }//GEN-LAST:event_jComboBoxGrupoFocusLost

    private void jComboBoxVoltagenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxVoltagenFocusLost
        ClassEvents.focusLostCombobox(jLabelVoltagem, jComboBoxVoltagen);
    }//GEN-LAST:event_jComboBoxVoltagenFocusLost

    private void jComboBoxFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorFocusLost
        ClassEvents.focusLostCombobox(jLabelFornecedor, jComboBoxFornecedor);
    }//GEN-LAST:event_jComboBoxFornecedorFocusLost

    private void jComboBoxStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxStatusFocusLost
        ClassEvents.focusLostCombobox(jLabelStatus, jComboBoxStatus);
    }//GEN-LAST:event_jComboBoxStatusFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxFornecedor;
    private javax.swing.JComboBox jComboBoxGrupo;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JComboBox jComboBoxVoltagen;
    private com.toedter.calendar.JDateChooser jDateChooserDataCompra;
    private com.toedter.calendar.JDateChooser jDateChooserFinalGarantia;
    private com.toedter.calendar.JDateChooser jDateChooserFinalGarantiaManutencao;
    private com.toedter.calendar.JDateChooser jDateChooserFinalVidaUtil;
    private com.toedter.calendar.JDateChooser jDateChooserInicioGarantiaManutencao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelDataCompra;
    private javax.swing.JLabel jLabelDescricaoDepreciacaoDiaria;
    private javax.swing.JLabel jLabelFimGarantiaManutencao;
    private javax.swing.JLabel jLabelFinalGarantia;
    private javax.swing.JLabel jLabelFinalVidaUtil;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelGarantia;
    private javax.swing.JLabel jLabelGarantiaManutencao;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelInicioGarantiaManutencao;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNomeBens;
    private javax.swing.JLabel jLabelNotaFiscal;
    private javax.swing.JLabel jLabelNumeroControle;
    private javax.swing.JLabel jLabelNumeroSerie;
    private javax.swing.JLabel jLabelObservacoes;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTempoUsoPorcento;
    private javax.swing.JLabel jLabelValorAtual;
    private javax.swing.JLabel jLabelValorCompra;
    private javax.swing.JLabel jLabelVidaUtil;
    private javax.swing.JLabel jLabelVoltagem;
    private javax.swing.JLabel jLabeltempoUso;
    private javax.swing.JPanel jPanelBens;
    private javax.swing.JPanel jPanelSecundario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBens;
    private javax.swing.JTextField jTextFieldDepreciacaoDiaria;
    private javax.swing.JTextField jTextFieldGarantia;
    private javax.swing.JTextField jTextFieldIdbens;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNomeBen;
    private javax.swing.JTextField jTextFieldNotalFiscal;
    private javax.swing.JTextField jTextFieldNumeroControle;
    private javax.swing.JTextField jTextFieldNumeroSerie;
    private javax.swing.JTextArea jTextFieldObservaçoes;
    private javax.swing.JTextField jTextFieldTempoUso;
    private javax.swing.JTextField jTextFieldTempoUsoPorcento;
    private javax.swing.JTextField jTextFieldValorAtual;
    private javax.swing.JTextField jTextFieldValorCompra;
    private javax.swing.JTextField jTextFieldVidaUtil;
    // End of variables declaration//GEN-END:variables

    private void preencherComboGrupo() {
        jComboBoxGrupo.removeAllItems();
        jComboBoxGrupo.addItem("Selecione um Grupo");

        @SuppressWarnings("UnusedAssignment")
        ArrayList<Object> objetos = new ArrayList<>();
        objetos = grupoDao.listarGrupos();

        for (Object objeto : objetos) {
            jComboBoxGrupo.addItem(objeto);
        }
    }

    private void preencherComboVoltagen() {
        jComboBoxVoltagen.removeAllItems();
        jComboBoxVoltagen.addItem("Selecione A Voltagem");
        jComboBoxVoltagen.addItem(" ");
        jComboBoxVoltagen.addItem("127 V");
        jComboBoxVoltagen.addItem("220 V");
        jComboBoxVoltagen.addItem("127/220 V");
        jComboBoxVoltagen.addItem("360 V");

    }

    private void preencherComboStatus() {
        jComboBoxStatus.removeAllItems();
        jComboBoxStatus.addItem("Selecione um Status");
        jComboBoxStatus.addItem("Ativo");
        jComboBoxStatus.addItem("Queimado");
        jComboBoxStatus.addItem("Manuteção");
        jComboBoxStatus.addItem("Descartado");

    }

    private void preencherComboFornecedor() {
        jComboBoxFornecedor.removeAllItems();
        jComboBoxFornecedor.addItem("Selecione um Fornecedor");
        @SuppressWarnings("UnusedAssignment")
        ArrayList<Object> objetos = new ArrayList<>();
        objetos = fornecedorDao.listarFornecedor();

        for (Object objeto : objetos) {
            jComboBoxFornecedor.addItem(objeto);
        }
    }

    private void limparCampos() {
        jDateChooserDataCompra.setDate(new Date());
        jTextFieldNumeroControle.setText("");
        jTextFieldNotalFiscal.setText("");
        jTextFieldValorCompra.setText("");
        jTextFieldValorCompra.setText("");
        jComboBoxGrupo.setSelectedIndex(0);
        jComboBoxFornecedor.setSelectedIndex(0);
        jTextFieldNumeroSerie.setText("");
        jTextFieldModelo.setText("");
        jComboBoxFornecedor.setSelectedIndex(0);
        jComboBoxStatus.setSelectedIndex(0);
        jTextFieldLocal.setText("");
        jTextFieldObservaçoes.setText("");
        jTextFieldNomeBen.setText("");
        jTextFieldGarantia.setText("");
        jTextFieldVidaUtil.setText("");
        //Limpado capos do Panel secundario
        jTextFieldDepreciacaoDiaria.setText("");
        jTextFieldValorAtual.setText("");
        jTextFieldTempoUso.setText("");
        jTextFieldTempoUsoPorcento.setText("");

    }

    private void cadastrarBens() {
        if (jComboBoxGrupo.getSelectedIndex() != 0 && jComboBoxStatus.getSelectedIndex() != 0
                && jComboBoxFornecedor.getSelectedIndex() != 0 && jComboBoxVoltagen.getSelectedIndex() != 0
                && !jTextFieldNomeBen.getText().equals("") && !jTextFieldNumeroControle.getText().equals("")
                && !jTextFieldValorCompra.getText().equals("") && !jTextFieldNotalFiscal.getText().equals("")
                && !jTextFieldNumeroSerie.getText().equals("") && !jTextFieldLocal.getText().equals("")) {

            bensTemp.setNome(jTextFieldNomeBen.getText());
            bensTemp.setNumeroControle(jTextFieldNumeroControle.getText());
            bensTemp.setNotaFiscal(jTextFieldNotalFiscal.getText());
            bensTemp.setValorCompra(Double.parseDouble(jTextFieldValorCompra.getText()));
            bensTemp.setVoltagem((String) jComboBoxFornecedor.getSelectedItem());
            bensTemp.setNumeroSerie(jTextFieldNumeroSerie.getText());
            bensTemp.setModelo(jTextFieldModelo.getText());
            bensTemp.setLocal(jTextFieldLocal.getText());
            bensTemp.setObservacoes(jTextFieldObservaçoes.getText());
            bensTemp.setStatus((String) jComboBoxStatus.getSelectedItem());
            bensTemp.setGarantia(jTextFieldGarantia.getText());
            bensTemp.setVidaUtil(jTextFieldVidaUtil.getText());
            bensTemp.setIdUsuarioCad((ClassUtils.getIdUsuario()));
            bensTemp.setIdUsuarioAlt((ClassUtils.getIdUsuario()));

            bensTemp.setDataCadastro(ClassUtils.setDateMsqy());
            bensTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
            bensTemp.setDataCompra(ClassUtils.setDateChooserMysql(jDateChooserDataCompra));

            bensDao.cadastraBens(bensTemp, (String) grupoDao.buscarIdGrupo(jComboBoxGrupo.getSelectedItem().toString()),
                    (String) fornecedorDao.getIdFornecedor(jComboBoxFornecedor.getSelectedItem().toString()));

            preencherTabela();
            limparCampos();
            modificadorCampos();
            jPanelBens.setVisible(false);
            jPanelSecundario.setVisible(false);
            jButtonNovo.setEnabled(true);
            jButtonExcluir.setEnabled(false);

        } else {
            jLabelNumeroControle.setForeground(Color.red);
            jLabelNotaFiscal.setForeground(Color.red);
            jLabelValorCompra.setForeground(Color.red);
            jLabelGrupo.setForeground(Color.red);
            jLabelVoltagem.setForeground(Color.red);
            jLabelNumeroSerie.setForeground(Color.red);
            jLabelModelo.setForeground(Color.red);
            jLabelFornecedor.setForeground(Color.red);
            jLabelStatus.setForeground(Color.red);
            jLabelLocal.setForeground(Color.red);
            jLabelNomeBens.setForeground(Color.red);
            jLabelGarantia.setForeground(Color.red);
            jLabelVidaUtil.setForeground(Color.red);
        }
    }

    private void validaCampos() {

        jTextFieldLocal.setDocument(new NumeroMaximoCaracters(20));
        jTextFieldModelo.setDocument(new NumeroMaximoCaracters(45));
        jTextFieldNomeBen.setDocument(new NumeroMaximoCaracters(45));
        jTextFieldNotalFiscal.setDocument(new SomenteNumero(10));
        jTextFieldNumeroControle.setDocument(new SomenteNumero(5));
        jTextFieldNumeroSerie.setDocument(new SomenteNumero(15));
        jTextFieldObservaçoes.setDocument(new NumeroMaximoCaracters(100));
        jTextFieldValorCompra.setDocument(new FormatDouble(9));
        jTextFieldGarantia.setDocument(new SomenteNumero(8));
        jTextFieldVidaUtil.setDocument(new SomenteNumero(5));
    }

    private void itensSelecionados() throws ParseException, Exception {
        limparCampos();
        int seleciona = jTableBens.getSelectedRow();

        jTextFieldNomeBen.setText(dados.get(seleciona).getNome());
        jTextFieldNumeroControle.setText(dados.get(seleciona).getNumeroControle());
        jTextFieldNotalFiscal.setText(dados.get(seleciona).getNotaFiscal());
        jTextFieldValorCompra.setText(String.valueOf(dados.get(seleciona).getValorCompra()));

        jDateChooserDataCompra.setDate(ClassUtils.setDateChoose(dados.get(seleciona).getDataCompra()));
        jDateChooserFinalGarantiaManutencao.setDate(ClassUtils.setDateChoose(dados.get(seleciona).getFinalGarantia()));
        jDateChooserInicioGarantiaManutencao.setDate(ClassUtils.setDateChoose(dados.get(seleciona).getInicioGarantia()));

        jComboBoxGrupo.setSelectedItem(grupoDao.buscarNomeGrupo(String.valueOf(dados.get(seleciona).getIdGrupo())));
        jComboBoxFornecedor.setSelectedItem(dados.get(seleciona).getVoltagem());
        jTextFieldNumeroSerie.setText(dados.get(seleciona).getNumeroSerie());
        jTextFieldModelo.setText(dados.get(seleciona).getModelo());
        jComboBoxFornecedor.setSelectedItem(fornecedorDao.getNomeFornecedor(String.valueOf(dados.get(seleciona).getIdFornecedor())));
        jTextFieldLocal.setText(dados.get(seleciona).getLocal());
        jComboBoxStatus.setSelectedItem(dados.get(seleciona).getStatus());
        jTextFieldObservaçoes.setText(dados.get(seleciona).getObservacoes());
        jTextFieldIdbens.setText(String.valueOf(dados.get(seleciona).getIdBens()));
        jTextFieldGarantia.setText(dados.get(seleciona).getGarantia());
        jTextFieldVidaUtil.setText(dados.get(seleciona).getVidaUtil());

        modificador = 2;
        modificadorCampos();
        panelSecundario();
        jTextFieldNomeBen.requestFocus();

    }

    private void preencherTabela() {

        String[] Colunas = new String[]{"Bens", "Localização", "Status", "Nº Controle ", "Nota Fiscal", "Nº Série", "Data Cadastro", "Última Auteração"};

        BensDao bensTempTabela = new BensDao();
        dados = bensTempTabela.listar();
        Tabela modelo = new TabelaBens(dados, Colunas);

        jTableBens.setModel(modelo);

        jTableBens.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTableBens.getColumnModel().getColumn(0).setResizable(false);

        jTableBens.getColumnModel().getColumn(1).setPreferredWidth(165);
        jTableBens.getColumnModel().getColumn(1).setResizable(false);

        jTableBens.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableBens.getColumnModel().getColumn(2).setResizable(false);

        jTableBens.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableBens.getColumnModel().getColumn(3).setResizable(false);

        jTableBens.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableBens.getColumnModel().getColumn(4).setResizable(false);

        jTableBens.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTableBens.getColumnModel().getColumn(5).setResizable(false);

        jTableBens.getColumnModel().getColumn(6).setPreferredWidth(325);
        jTableBens.getColumnModel().getColumn(6).setResizable(false);

        jTableBens.getColumnModel().getColumn(7).setPreferredWidth(325);
        jTableBens.getColumnModel().getColumn(7).setResizable(false);

        jTableBens.getTableHeader().setReorderingAllowed(false);
        jTableBens.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableBens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    private void editarBens() {
        if (jComboBoxGrupo.getSelectedIndex() != 0 && jComboBoxStatus.getSelectedIndex() != 0
                && jComboBoxFornecedor.getSelectedIndex() != 0 && jComboBoxVoltagen.getSelectedIndex() != 0
                && !jTextFieldNomeBen.getText().equals("") && !jTextFieldNumeroControle.getText().equals("")
                && !jTextFieldValorCompra.getText().equals("") && !jTextFieldNotalFiscal.getText().equals("")
                && !jTextFieldNumeroSerie.getText().equals("") && !jTextFieldLocal.getText().equals("")) {

            bensTemp.setNome(jTextFieldNomeBen.getText());
            bensTemp.setNumeroControle(jTextFieldNumeroControle.getText());
            bensTemp.setNotaFiscal(jTextFieldNotalFiscal.getText());
            bensTemp.setValorCompra(Double.parseDouble(jTextFieldValorCompra.getText()));
            bensTemp.setVoltagem((String) jComboBoxVoltagen.getSelectedItem());
            bensTemp.setNumeroSerie(jTextFieldNumeroSerie.getText());
            bensTemp.setModelo(jTextFieldModelo.getText());
            bensTemp.setLocal(jTextFieldLocal.getText());
            bensTemp.setObservacoes(jTextFieldObservaçoes.getText());
            bensTemp.setStatus((String) jComboBoxStatus.getSelectedItem());

            bensTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
            bensTemp.setDataCompra(ClassUtils.setDateChooserMysql(jDateChooserDataCompra));
            bensTemp.setIdBens(Integer.parseInt(jTextFieldIdbens.getText()));
            bensTemp.setGarantia(jTextFieldGarantia.getText());
            bensTemp.setVidaUtil(jTextFieldVidaUtil.getText());
            bensTemp.setIdUsuarioAlt((ClassUtils.getIdUsuario()));

            bensDao.atualizarBens(bensTemp, (String) grupoDao.buscarIdGrupo(jComboBoxGrupo.getSelectedItem().toString()),
                    Integer.parseInt(fornecedorDao.getIdFornecedor(jComboBoxFornecedor.getSelectedItem().toString())));

            preencherTabela();
            limparCampos();
            modificadorCampos();
            jPanelBens.setVisible(false);
            jPanelSecundario.setVisible(false);
            jButtonNovo.setEnabled(true);
            jButtonExcluir.setEnabled(false);
        } else {
            jLabelNumeroControle.setForeground(Color.red);
            jLabelNotaFiscal.setForeground(Color.red);
            jLabelValorCompra.setForeground(Color.red);
            jLabelGrupo.setForeground(Color.red);
            jLabelVoltagem.setForeground(Color.red);
            jLabelNumeroSerie.setForeground(Color.red);
            jLabelModelo.setForeground(Color.red);
            jLabelFornecedor.setForeground(Color.red);
            jLabelStatus.setForeground(Color.red);
            jLabelLocal.setForeground(Color.red);
            jLabelNomeBens.setForeground(Color.red);
            jLabelGarantia.setForeground(Color.red);
            jLabelVidaUtil.setForeground(Color.red);
        }
    }

    private void deletarBens() {
        bensTemp.setIdBens(Integer.parseInt(jTextFieldIdbens.getText()));

        bensDao.deletar(bensTemp);
        limparCampos();
        preencherTabela();
        jPanelBens.setVisible(false);
        jPanelSecundario.setVisible(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        modificador = 1;
    }

    private void modificadorCampos() {
        jLabelNumeroControle.setForeground(Color.BLACK);
        jLabelNotaFiscal.setForeground(Color.BLACK);
        jLabelValorCompra.setForeground(Color.BLACK);
        jLabelGrupo.setForeground(Color.BLACK);
        jLabelVoltagem.setForeground(Color.BLACK);
        jLabelNumeroSerie.setForeground(Color.BLACK);
        jLabelModelo.setForeground(Color.BLACK);
        jLabelFornecedor.setForeground(Color.BLACK);
        jLabelStatus.setForeground(Color.BLACK);
        jLabelLocal.setForeground(Color.BLACK);
        jLabelNomeBens.setForeground(Color.BLACK);
        jLabelGarantia.setForeground(Color.BLACK);
        jLabelVidaUtil.setForeground(Color.BLACK);

    }

    private void panelSecundario() {
        //Calculando termino da garatia     
        jDateChooserFinalGarantia.setDate(new Date(ClassUtils.somarDias(jDateChooserDataCompra, jTextFieldGarantia)));
        finalGarantia(jLabelFinalGarantia, jDateChooserFinalGarantia);

        //Calculando termino vida Util
        jDateChooserFinalVidaUtil.setDate(new Date(ClassUtils.somarDias(jDateChooserDataCompra, jTextFieldVidaUtil)));
        finalVidaUtil(jLabelFinalVidaUtil, jDateChooserFinalVidaUtil);
        //Calculando total de Dias
        totalDias(jDateChooserDataCompra, jTextFieldTempoUso);

        //Calculando depreciação diaria
        Double depreciacaoDiaria = Double.parseDouble(jTextFieldValorCompra.getText())
                / Double.parseDouble(jTextFieldVidaUtil.getText());
        String valorDepreciacao = String.format("%.2f", depreciacaoDiaria);
        jTextFieldDepreciacaoDiaria.setText("R$: " + valorDepreciacao);

        //calculando valor atual        
        Double valorAtual = Double.parseDouble(jTextFieldValorCompra.getText())
                - (depreciacaoDiaria * Double.parseDouble(jTextFieldTempoUso.getText()));
        String valor = String.format("%.2f", valorAtual);
        jTextFieldValorAtual.setText("R$: " + valor);
        if (valorAtual <= 0) {
            jTextFieldValorAtual.setBackground(Color.red);
            jLabelValorAtual.setForeground(Color.red);
        } else {
            jTextFieldValorAtual.setBackground(Color.WHITE);
            jLabelValorAtual.setForeground(Color.BLACK);
        }

        //Calculando tempo de uso em porcentagen
        Double tempoUso = Double.parseDouble(jTextFieldTempoUso.getText());
        Double vidaUtil = Double.parseDouble(jTextFieldVidaUtil.getText());
        Double calculo = (tempoUso / vidaUtil) * 100;
        String tempoUsoPorcento = String.valueOf(String.format("%.2f", calculo));
        jTextFieldTempoUsoPorcento.setText(tempoUsoPorcento + "%");
        garantiaManutencao(jLabelInicioGarantiaManutencao, jLabelFimGarantiaManutencao,
                jLabelGarantiaManutencao, jDateChooserFinalGarantiaManutencao);
    }

    private void finalGarantia(JLabel label, JDateChooser date) {
        String finalGarantia = ClassUtils.setDateChooserMysql(date).replace("-", "");

        if (Integer.parseInt(dataAtual()) > Integer.parseInt(finalGarantia)) {
            label.setForeground(Color.red);
            date.setBackground(Color.red);
        } else {
            date.setBackground(Color.BLACK);
            label.setForeground(Color.BLACK);
        }
    }

    private void garantiaManutencao(JLabel labelInicio, JLabel labelFim,
            JLabel label, JDateChooser fim) {

        String finalGarantia = ClassUtils.setDateChooserMysql(fim).replace("-", "");
        if (!finalGarantia.equals("20000101")) {
            jLabelGarantiaManutencao.setVisible(true);
            jLabelFimGarantiaManutencao.setVisible(true);
            jLabelInicioGarantiaManutencao.setVisible(true);
            jDateChooserFinalGarantiaManutencao.setVisible(true);
            jDateChooserInicioGarantiaManutencao.setVisible(true);
            if (Integer.parseInt(dataAtual()) > Integer.parseInt(finalGarantia)) {
                label.setForeground(Color.red);
                fim.setBackground(Color.red);
                labelFim.setForeground(Color.red);
                labelInicio.setForeground(Color.red);

            } else {

                fim.setBackground(Color.BLACK);
                label.setForeground(Color.BLACK);
                labelFim.setForeground(Color.BLACK);
                labelInicio.setForeground(Color.BLACK);
            }
        } else {
            jLabelGarantiaManutencao.setVisible(false);
            jLabelFimGarantiaManutencao.setVisible(false);
            jLabelInicioGarantiaManutencao.setVisible(false);
            jDateChooserFinalGarantiaManutencao.setVisible(false);
            jDateChooserInicioGarantiaManutencao.setVisible(false);
        }

    }

    private void totalDias(JDateChooser date, JTextField text) {
        String dataCompra = ClassUtils.setDateChooserMysql(date).replace("-", "");
        int dias = Integer.parseInt(dataAtual()) - Integer.parseInt(dataCompra);
        text.setText(String.valueOf(dias));

    }

    private String dataAtual() {
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("yyyyMMdd");
        String dataAtual = hoje.format(formatador);
        return dataAtual;
    }

    private void finalVidaUtil(JLabel label, JDateChooser date) {
        String finalVidaUtil = ClassUtils.setDateChooserMysql(date).replace("-", "");

        if (Integer.parseInt(dataAtual()) > Integer.parseInt(finalVidaUtil)) {
            label.setForeground(Color.red);
            date.setBackground(Color.red);
        } else {
            date.setBackground(Color.BLACK);
            label.setForeground(Color.BLACK);
        }
    }

    private void enventFocus() {
        ArrayList<Component> order = new ArrayList<>();
        order.add(jTextFieldNomeBen);
        order.add(jTextFieldNumeroControle);
        order.add(jTextFieldLocal);
        order.add(jTextFieldModelo);
        order.add(jTextFieldNumeroSerie);
        order.add(jComboBoxGrupo);
        order.add(jComboBoxVoltagen);
        order.add(jComboBoxFornecedor);
        order.add(jComboBoxStatus);
        order.add(jTextFieldNotalFiscal);
        order.add(jTextFieldValorCompra);
        order.add(jTextFieldGarantia);
        order.add(jTextFieldVidaUtil);
        order.add(jButtonSalvar);
        order.add(jButtonCancelar);
        
        FocusLost focus = new FocusLost(order);
        setFocusTraversalPolicy(focus);
    }

    }
