/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wss.viwer;

import br.com.wss.dao.CidadeDao;
import br.com.wss.dao.EnderecoDao;
import br.com.wss.dao.EstadoDao;
import br.com.wss.dao.FornecedorDao;
import br.com.wss.dao.PaisDao;
import br.com.wss.modelo.Endereco;
import br.com.wss.modelo.Fornecedor;
import br.com.wss.tabelas.Tabela;
import br.com.wss.tabelas.TabelaFornecedor;
import br.com.wss.utilidades.ClassEvents;
import br.com.wss.utilidades.ClassUtils;
import br.com.wss.utilidades.FocusLost;
import br.com.wss.utilidades.NumeroMaximoCaracters;
import br.com.wss.utilidades.SomenteNumero;
import br.com.wss.utilidades.ValidaCPFCNPJ;
import br.com.wss.utilidades.WebServiceCep;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author William
 */
public class FrmFornecedor extends javax.swing.JInternalFrame {

    int modificador = 1;
    String idEstado;

    CidadeDao cidadeDao = new CidadeDao();
    EstadoDao estadoDao = new EstadoDao();
    PaisDao paisDao = new PaisDao();
    FornecedorDao fornecedorDao = new FornecedorDao();
    EnderecoDao enderecoDao = new EnderecoDao();
    Fornecedor fornecedorTemp = new Fornecedor();
    Endereco enderecoTemp = new Endereco();
    ArrayList<Fornecedor> dadosFornecedor;

    /**
     * Creates new form FrmFornecedor
     */
    public FrmFornecedor() {
        initComponents();
        preencherComboEstado();
        preencherComboPais();
        preencherTabela();
        jPanel2.setVisible(false);
        jButtonExcluir.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxEstado.setEnabled(false);
        jTextFieldIdFornecedor.setVisible(false);
        jComboBoxCidade.removeAllItems();
        jComboBoxCidade.addItem("Selecione uma Cidade");

        validaCampos();
        eventFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelRazaoSocial = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jLabelResponsavel = new javax.swing.JLabel();
        jTextFieldResponsavel = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jComboBoxCidade = new javax.swing.JComboBox();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldIdFornecedor = new javax.swing.JTextField();
        jLabelCnpj = new javax.swing.JLabel();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelPias = new javax.swing.JLabel();
        jComboBoxPais = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextFieldCep = new javax.swing.JFormattedTextField();
        jTextFieldCnpj = new javax.swing.JFormattedTextField();
        jTextFieldCelular = new javax.swing.JFormattedTextField();
        jTextFieldTelefone = new javax.swing.JFormattedTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Fornecedor");

        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFornecedor);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fornecedor"));
        jPanel2.setLayout(null);

        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(700, 30, 180, 26);

        jLabelRazaoSocial.setText("Razão Social:");
        jPanel2.add(jLabelRazaoSocial);
        jLabelRazaoSocial.setBounds(20, 60, 80, 20);

        jTextFieldRazaoSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRazaoSocialFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldRazaoSocial);
        jTextFieldRazaoSocial.setBounds(110, 60, 180, 26);

        jLabelResponsavel.setText("Responsavel");
        jPanel2.add(jLabelResponsavel);
        jLabelResponsavel.setBounds(20, 90, 80, 20);

        jTextFieldResponsavel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldResponsavelFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldResponsavel);
        jTextFieldResponsavel.setBounds(110, 90, 180, 26);

        jButtonSalvar.setText("Variavel");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });
        jPanel2.add(jButtonSalvar);
        jButtonSalvar.setBounds(100, 190, 71, 28);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);
        jButtonCancelar.setBounds(210, 190, 80, 28);

        jLabelTelefone.setText("Telefone:");
        jPanel2.add(jLabelTelefone);
        jLabelTelefone.setBounds(310, 30, 80, 20);

        jLabelCelular.setText("Celular:");
        jPanel2.add(jLabelCelular);
        jLabelCelular.setBounds(20, 150, 80, 20);

        jLabelEstado.setText("Estado:");
        jPanel2.add(jLabelEstado);
        jLabelEstado.setBounds(310, 120, 80, 20);

        jLabelCidade.setText("Cidade:");
        jPanel2.add(jLabelCidade);
        jLabelCidade.setBounds(310, 150, 80, 20);

        jLabelBairro.setText("Bairro:");
        jPanel2.add(jLabelBairro);
        jLabelBairro.setBounds(600, 30, 90, 20);

        jLabelNumero.setText("Numero:");
        jPanel2.add(jLabelNumero);
        jLabelNumero.setBounds(600, 90, 90, 20);

        jTextFieldNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldNumero);
        jTextFieldNumero.setBounds(700, 90, 180, 26);

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxCidadeFocusLost(evt);
            }
        });
        jPanel2.add(jComboBoxCidade);
        jComboBoxCidade.setBounds(400, 150, 180, 26);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxEstadoFocusLost(evt);
            }
        });
        jComboBoxEstado.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxEstadoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(400, 120, 180, 26);

        jLabelEmail.setText("E-mail:");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(20, 120, 80, 20);

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(110, 120, 180, 26);

        jTextFieldEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(700, 60, 180, 26);

        jLabelEndereco.setText("Endereço:");
        jPanel2.add(jLabelEndereco);
        jLabelEndereco.setBounds(600, 60, 90, 20);

        jLabelCep.setText("Cep:");
        jPanel2.add(jLabelCep);
        jLabelCep.setBounds(310, 60, 80, 20);

        jTextFieldIdFornecedor.setText("ID");
        jPanel2.add(jTextFieldIdFornecedor);
        jTextFieldIdFornecedor.setBounds(20, 190, 50, 30);

        jLabelCnpj.setText("CNPJ:");
        jPanel2.add(jLabelCnpj);
        jLabelCnpj.setBounds(20, 30, 80, 20);

        jLabelComplemento.setText("Complemento:");
        jPanel2.add(jLabelComplemento);
        jLabelComplemento.setBounds(600, 120, 90, 20);
        jPanel2.add(jTextFieldComplemento);
        jTextFieldComplemento.setBounds(700, 120, 180, 26);

        jLabelPias.setText("Pais:");
        jPanel2.add(jLabelPias);
        jLabelPias.setBounds(310, 90, 80, 20);

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxPaisFocusLost(evt);
            }
        });
        jComboBoxPais.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxPaisPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(jComboBoxPais);
        jComboBoxPais.setBounds(400, 90, 180, 26);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(505, 60, 75, 26);

        try {
            jTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCepFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldCep);
        jTextFieldCep.setBounds(400, 60, 100, 26);

        try {
            jTextFieldCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCnpjFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldCnpj);
        jTextFieldCnpj.setBounds(110, 30, 180, 26);

        try {
            jTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCelularFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldCelular);
        jTextFieldCelular.setBounds(110, 150, 180, 26);

        try {
            jTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefoneFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(400, 30, 180, 26);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovo)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(545, 805, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        if (modificador == 1) {
            jPanel2.setVisible(true);
            jButtonExcluir.setEnabled(false);
            jButtonNovo.setEnabled(false);
            limparCampos();
            jButtonSalvar.setText("Salvar");
        } else {
            modificador = 1;
            jPanel2.setVisible(true);
            jButtonExcluir.setEnabled(false);
            jButtonNovo.setEnabled(false);
            limparCampos();
            jButtonSalvar.setText("Salvar");
        }

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jPanel2.setVisible(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxEstado.setEnabled(false);
        limparCampos();
        modificador = 1;

        modificadorCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (modificador == 1) {
            jButtonSalvar.setText("Salvar");
            cadastrarFornecedor();

        } else if (modificador == 2) {
            jButtonSalvar.setText("Editar");
            editarFornecedor();
        } else {

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        deletarFornecedor();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxEstadoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxEstadoPopupMenuWillBecomeInvisible
        preencherComboCidade();
        jComboBoxCidade.setEnabled(true);
    }//GEN-LAST:event_jComboBoxEstadoPopupMenuWillBecomeInvisible

    private void jTableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                comboCidade();
                comboEstado();
                itensSelecionados();
            } catch (Exception ex) {
                Logger.getLogger(FrmBens.class.getName()).log(Level.SEVERE, null, ex);
            }
            jPanel2.setVisible(true);
            jButtonNovo.setEnabled(false);
            jButtonExcluir.setEnabled(true);
            modificador = 2;
            jButtonSalvar.setText("Editar");
        }
    }//GEN-LAST:event_jTableFornecedorMouseClicked

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        if (modificador == 1) {
            jButtonSalvar.setText("Salvar");
            cadastrarFornecedor();

        } else if (modificador == 2) {
            jButtonSalvar.setText("Editar");
            editarFornecedor();
        } else {

        }
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jTextFieldRazaoSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRazaoSocialFocusLost
        ClassEvents.focusLostTextField(jLabelRazaoSocial, jTextFieldRazaoSocial);
    }//GEN-LAST:event_jTextFieldRazaoSocialFocusLost

    private void jTextFieldResponsavelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldResponsavelFocusLost
        ClassEvents.focusLostTextField(jLabelResponsavel, jTextFieldResponsavel);
    }//GEN-LAST:event_jTextFieldResponsavelFocusLost

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        ClassEvents.focusLostTextField(jLabelEmail, jTextFieldEmail);
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        ClassEvents.focusLostTextField(jLabelBairro, jTextFieldBairro);
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFocusLost
        ClassEvents.focusLostTextField(jLabelEndereco, jTextFieldEndereco);
    }//GEN-LAST:event_jTextFieldEnderecoFocusLost

    private void jTextFieldNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFocusLost
        ClassEvents.focusLostTextField(jLabelNumero, jTextFieldNumero);
    }//GEN-LAST:event_jTextFieldNumeroFocusLost

    private void jComboBoxEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxEstadoFocusLost
        ClassEvents.focusLostCombobox(jLabelEstado, jComboBoxEstado);
        preencherComboCidade();
        jComboBoxCidade.setEnabled(true);
    }//GEN-LAST:event_jComboBoxEstadoFocusLost

    private void jComboBoxCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCidadeFocusLost
        ClassEvents.focusLostCombobox(jLabelCidade, jComboBoxCidade);
    }//GEN-LAST:event_jComboBoxCidadeFocusLost

    private void jComboBoxPaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxPaisFocusLost
        ClassEvents.focusLostCombobox(jLabelPias, jComboBoxPais);
        preencherComboEstado();
        jComboBoxEstado.setEnabled(true);
    }//GEN-LAST:event_jComboBoxPaisFocusLost

    private void jComboBoxPaisPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxPaisPopupMenuWillBecomeInvisible
        ClassEvents.focusLostCombobox(jLabelPias, jComboBoxPais);
        preencherComboEstado();
        jComboBoxEstado.setEnabled(true);
    }//GEN-LAST:event_jComboBoxPaisPopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscaCep();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCepFocusLost
        String cep = jTextFieldCep.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
        if (cep.length() < 8
                || cep.equals("11111111") || cep.equals("22222222") || cep.equals("33333333")
                || cep.equals("44444444") || cep.equals("55555555") || cep.equals("66666666")
                || cep.equals("77777777") || cep.equals("88888888") || cep.equals("99999999")) {
            jLabelCep.setForeground(Color.red);
            jTextFieldCep.setText("");
        } else if (!jTextFieldCep.getText().equals("     -   ")) {
            jLabelCep.setForeground(Color.BLACK);
        } else {
            jLabelCep.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldCepFocusLost

    private void jTextFieldCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCnpjFocusLost
        String cnpj = jTextFieldCnpj.getText().replace(" ", "").replace(".", "").replace("/", "").replace("-", "");
        if (ValidaCPFCNPJ.isValidCNPJ(cnpj)) {
            jLabelCnpj.setForeground(Color.BLACK);
        } else {
            jLabelCnpj.setForeground(Color.red);
            jTextFieldCnpj.setText("");
        }
    }//GEN-LAST:event_jTextFieldCnpjFocusLost

    private void jTextFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneFocusLost
        String telefone = jTextFieldTelefone.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
        if (telefone.length() < 10
                || telefone.equals("0000000000") || telefone.equals("2222222222") || telefone.equals("3333333333")
                || telefone.equals("4444444444") || telefone.equals("5555555555") || telefone.equals("6666666666")
                || telefone.equals("7777777777") || telefone.equals("8888888888") || telefone.equals("9999999999")) {
            jTextFieldTelefone.setText("");
            jLabelTelefone.setForeground(Color.red);
        } else if (!jTextFieldTelefone.getText().equals("(  )     -    ")) {
            jLabelTelefone.setForeground(Color.BLACK);
        } else {
            jLabelTelefone.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldTelefoneFocusLost

    private void jTextFieldCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCelularFocusLost
        String celular = jTextFieldCelular.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
        if (celular.length() < 11
                || celular.equals("00000000000") || celular.equals("22222222222") || celular.equals("33333333333")
                || celular.equals("44444444444") || celular.equals("55555555555") || celular.equals("66666666666")
                || celular.equals("77777777777") || celular.equals("88888888888") || celular.equals("99999999999")) {
            jLabelCelular.setForeground(Color.red);
            jTextFieldCelular.setText("");

        } else if (!jTextFieldCelular.getText().equals("(  )       -    ")) {
            jLabelCelular.setForeground(Color.BLACK);
        } else {
            jLabelCelular.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldCelularFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxPais;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCnpj;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPias;
    private javax.swing.JLabel jLabelRazaoSocial;
    private javax.swing.JLabel jLabelResponsavel;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JFormattedTextField jTextFieldCelular;
    private javax.swing.JFormattedTextField jTextFieldCep;
    private javax.swing.JFormattedTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldIdFornecedor;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JFormattedTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables

    private void cadastrarFornecedor() {
        if (valida()) {
            String celular = jTextFieldCelular.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
            fornecedorTemp.setCelular(Long.parseLong(celular));
            String cnpj = jTextFieldCnpj.getText().replace(" ", "").replace(".", "").replace("/", "").replace("-", "");
            fornecedorTemp.setCnpj(Long.parseLong(cnpj));
            fornecedorTemp.setDataCadastro(ClassUtils.setDateMsqy());
            fornecedorTemp.setEmail(jTextFieldEmail.getText());
            fornecedorTemp.setRazaoSocial(jTextFieldRazaoSocial.getText());
            fornecedorTemp.setResponsavel(jTextFieldResponsavel.getText());
            String telefone = jTextFieldTelefone.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
            fornecedorTemp.setTelefone(telefone);
            fornecedorTemp.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            fornecedorTemp.setReferencia(jTextFieldComplemento.getText());
            fornecedorTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
            fornecedorTemp.setUsuarioCad(ClassUtils.getIdUsuario());
            fornecedorTemp.setUsuarioAlt(ClassUtils.getIdUsuario());

            enderecoTemp.setBairro(jTextFieldBairro.getText());
            String cep = jTextFieldCep.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
            enderecoTemp.setCep(Integer.parseInt(cep));
            enderecoTemp.setRua(jTextFieldEndereco.getText());
            enderecoTemp.setIdCidade(Integer.parseInt(cidadeDao.getIdCidade((String) jComboBoxCidade.getSelectedItem())));

            if (enderecoDao.getEndereco(Integer.parseInt(cep))) {

                fornecedorTemp.setIdEndereco(Integer.parseInt(enderecoDao.getIdEndereco(cep)));

                if (fornecedorDao.cadastra(fornecedorTemp)) {
                    limparCampos();
                    preencherTabela();
                    jPanel2.setVisible(false);
                    jButtonNovo.setEnabled(true);
                }
            } else {
                if (enderecoDao.cadastra(enderecoTemp)) {
                    fornecedorTemp.setIdEndereco(Integer.parseInt(enderecoDao.getIdEndereco(cep)));
                    if (fornecedorDao.cadastra(fornecedorTemp)) {
                        limparCampos();
                        preencherTabela();
                        jPanel2.setVisible(false);
                        jButtonNovo.setEnabled(true);
                    }
                }
            }

        }
    }

    private void editarFornecedor() {
        if (valida()) {
            String celular = jTextFieldCelular.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
            fornecedorTemp.setCelular(Long.parseLong(celular));
            String cnpj = jTextFieldCnpj.getText().replace(" ", "").replace(".", "").replace("/", "").replace("-", "");
            fornecedorTemp.setCnpj(Long.parseLong(cnpj));
            fornecedorTemp.setDataCadastro(ClassUtils.setDateMsqy());
            fornecedorTemp.setEmail(jTextFieldEmail.getText());
            fornecedorTemp.setRazaoSocial(jTextFieldRazaoSocial.getText());
            fornecedorTemp.setResponsavel(jTextFieldResponsavel.getText());
            String telefone = jTextFieldTelefone.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
            fornecedorTemp.setTelefone(telefone);
            fornecedorTemp.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            fornecedorTemp.setReferencia(jTextFieldComplemento.getText());
            fornecedorTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
            fornecedorTemp.setUsuarioCad(ClassUtils.getIdUsuario());
            fornecedorTemp.setUsuarioAlt(ClassUtils.getIdUsuario());
            fornecedorTemp.setIdFornecedor(Integer.parseInt(jTextFieldIdFornecedor.getText()));

            enderecoTemp.setBairro(jTextFieldBairro.getText());
            String cep = jTextFieldCep.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
            enderecoTemp.setCep(Integer.parseInt(cep));
            enderecoTemp.setRua(jTextFieldEndereco.getText());
            enderecoTemp.setIdCidade(Integer.parseInt(cidadeDao.getIdCidade((String) jComboBoxCidade.getSelectedItem())));

            fornecedorTemp.setEndereco(enderecoTemp);

            if (enderecoDao.getEndereco(Integer.parseInt(cep))) {
                fornecedorTemp.setIdEnderecoFornecedor(Integer.parseInt(enderecoDao.getIdEndereco(cep)));
                if (fornecedorDao.atualizar(fornecedorTemp)) {
                    limparCampos();
                    preencherTabela();
                    jPanel2.setVisible(false);
                    jButtonNovo.setEnabled(true);
                }
            } else {
                if (enderecoDao.atualizar(enderecoTemp)) {
                    enderecoDao.cadastra(enderecoTemp);
                    fornecedorTemp.setIdEnderecoFornecedor(Integer.parseInt(enderecoDao.getIdEndereco(cep)));
                    if (fornecedorDao.atualizar(fornecedorTemp)) {
                        limparCampos();
                        preencherTabela();
                        jPanel2.setVisible(false);
                        jButtonNovo.setEnabled(true);
                    }
                }
            }

        }

    }

    private void limparCampos() {
        jComboBoxEstado.setSelectedIndex(0);
        jComboBoxCidade.setSelectedIndex(0);
        jComboBoxPais.setSelectedIndex(0);
        jTextFieldBairro.setText("");
        jTextFieldCelular.setText("");
        jTextFieldCep.setText("");
        jTextFieldResponsavel.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldRazaoSocial.setText("");
        jTextFieldNumero.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldCnpj.setText("");
        jTextFieldComplemento.setText("");
    }

    private void deletarFornecedor() {
        fornecedorTemp.setIdFornecedor(Integer.parseInt(jTextFieldIdFornecedor.getText()));

        if (fornecedorDao.deletar(fornecedorTemp)) {
            limparCampos();
            preencherTabela();
            jPanel2.setVisible(false);
            jButtonNovo.setEnabled(true);
            jButtonExcluir.setEnabled(false);
            jComboBoxCidade.setEnabled(false);
            modificador = 1;
        }
    }

    private void modificadorCampos() {
        jLabelCnpj.setForeground(Color.BLACK);
        jLabelResponsavel.setForeground(Color.BLACK);
        jLabelCelular.setForeground(Color.BLACK);
        jLabelBairro.setForeground(Color.BLACK);
        jLabelEstado.setForeground(Color.BLACK);
        jLabelRazaoSocial.setForeground(Color.BLACK);
        jLabelCidade.setForeground(Color.BLACK);
        jLabelNumero.setForeground(Color.BLACK);
        jLabelTelefone.setForeground(Color.BLACK);
        jLabelEndereco.setForeground(Color.BLACK);
        jLabelCep.setForeground(Color.BLACK);
        jLabelEmail.setForeground(Color.BLACK);
        jLabelCnpj.setForeground(Color.BLACK);
        jLabelPias.setForeground(Color.BLACK);
        jLabelComplemento.setForeground(Color.BLACK);
    }

    private void preencherComboCidade() {
        jComboBoxCidade.removeAllItems();
        jComboBoxCidade.addItem("Selecione uma Cidade");
        if (jComboBoxEstado.getSelectedIndex() != 0) {
            idEstado = (String) estadoDao.buscarIdEstado(jComboBoxEstado.getSelectedItem().toString());
            @SuppressWarnings("UnusedAssignment")
            ArrayList<Object> objetos = new ArrayList<>();
            objetos = cidadeDao.listarCidade(idEstado);

            for (Object objeto : objetos) {
                jComboBoxCidade.addItem(objeto);
            }
        }
    }

    private void preencherComboEstado() {
        jComboBoxEstado.removeAllItems();
        jComboBoxEstado.addItem("Selecione um Estado");
        if (jComboBoxPais.getSelectedIndex() != 0) {
            System.out.println("pais " + (String) paisDao.buscarIdPais(jComboBoxPais.getSelectedItem().toString()));
            String idPais = (String) paisDao.buscarIdPais(jComboBoxPais.getSelectedItem().toString());
            @SuppressWarnings("UnusedAssignment")
            ArrayList<Object> objetos = new ArrayList<>();
            objetos = estadoDao.listarEstado(idPais);

            for (Object objeto : objetos) {
                jComboBoxEstado.addItem(objeto);
            }
        }
    }

    private void preencherComboPais() {
        jComboBoxPais.removeAllItems();
        jComboBoxPais.addItem("Selecione um Pais");

        @SuppressWarnings("UnusedAssignment")
        ArrayList<Object> objetos = new ArrayList<>();
        objetos = paisDao.listarPais();

        for (Object objeto : objetos) {
            jComboBoxPais.addItem(objeto);
        }

    }

    private void preencherTabela() {
        String[] Colunas = new String[]{"Fornecedor", "Contato", "Celular", "Telefone", "Estado", "Cidade", " Data Cadastro ", "Última Alteração"};

        FornecedorDao fornecedorTempTabela = new FornecedorDao();
        dadosFornecedor = fornecedorTempTabela.listar();
        Tabela modelo = new TabelaFornecedor(dadosFornecedor, Colunas);

        jTableFornecedor.setModel(modelo);

        jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTableFornecedor.getColumnModel().getColumn(0).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(165);
        jTableFornecedor.getColumnModel().getColumn(1).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableFornecedor.getColumnModel().getColumn(2).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableFornecedor.getColumnModel().getColumn(3).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableFornecedor.getColumnModel().getColumn(4).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableFornecedor.getColumnModel().getColumn(5).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(6).setPreferredWidth(300);
        jTableFornecedor.getColumnModel().getColumn(6).setResizable(false);

        jTableFornecedor.getColumnModel().getColumn(7).setPreferredWidth(300);
        jTableFornecedor.getColumnModel().getColumn(7).setResizable(false);

        jTableFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableFornecedor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableFornecedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void itensSelecionados() {
        limparCampos();
        jComboBoxCidade.setEnabled(true);
        jComboBoxEstado.setEnabled(true);

        int seleciona = jTableFornecedor.getSelectedRow();
        jTextFieldCnpj.setText(String.valueOf(dadosFornecedor.get(seleciona).getCnpj()));
        jTextFieldCelular.setText(String.valueOf(dadosFornecedor.get(seleciona).getCelular()));
        jTextFieldResponsavel.setText(dadosFornecedor.get(seleciona).getResponsavel());
        jTextFieldEmail.setText(dadosFornecedor.get(seleciona).getEmail());
        jTextFieldRazaoSocial.setText(dadosFornecedor.get(seleciona).getRazaoSocial());
        jTextFieldNumero.setText(String.valueOf(dadosFornecedor.get(seleciona).getNumero()));
        jTextFieldTelefone.setText(dadosFornecedor.get(seleciona).getTelefone());
        jTextFieldIdFornecedor.setText(String.valueOf(dadosFornecedor.get(seleciona).getIdFornecedor()));
        jTextFieldComplemento.setText(dadosFornecedor.get(seleciona).getReferencia());
        jTextFieldEndereco.setText(dadosFornecedor.get(seleciona).getRua());
        jTextFieldCep.setText(String.valueOf(dadosFornecedor.get(seleciona).getCep()));
        jTextFieldBairro.setText(dadosFornecedor.get(seleciona).getBairro());
        jComboBoxEstado.setSelectedItem(dadosFornecedor.get(seleciona).getNomeEstado());
        jComboBoxCidade.setSelectedItem(dadosFornecedor.get(seleciona).getNomeCidade());
        jComboBoxPais.setSelectedItem(dadosFornecedor.get(seleciona).getNomePais());

        modificador = 2;
        modificadorCampos();
    }

    private void validaCampos() {
        jTextFieldRazaoSocial.setDocument(new NumeroMaximoCaracters(45));
        jTextFieldResponsavel.setDocument(new NumeroMaximoCaracters(20));
        jTextFieldEmail.setDocument(new NumeroMaximoCaracters(45));
        jTextFieldBairro.setDocument(new NumeroMaximoCaracters(45));
        jTextFieldEndereco.setDocument(new NumeroMaximoCaracters(45));
        jTextFieldNumero.setDocument(new SomenteNumero(5));
        jTextFieldComplemento.setDocument(new NumeroMaximoCaracters(45));

    }

    private void comboCidade() {
        jComboBoxCidade.removeAllItems();
        jComboBoxCidade.addItem("Selecione uma Cidade");

        @SuppressWarnings("UnusedAssignment")
        ArrayList<Object> objetos = new ArrayList<>();
        objetos = cidadeDao.listarTodasCidade();

        for (Object objeto : objetos) {
            jComboBoxCidade.addItem(objeto);
        }
    }

    private void comboEstado() {
        jComboBoxEstado.removeAllItems();
        jComboBoxEstado.addItem("Selecione um Estado");

        @SuppressWarnings("UnusedAssignment")
        ArrayList<Object> objetos = new ArrayList<>();
        objetos = estadoDao.listarEstados();

        for (Object objeto : objetos) {
            jComboBoxEstado.addItem(objeto);
        }
    }

    private boolean valida() {
        boolean retorno = true;

        String celular = jTextFieldCelular.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
        String cnpj = jTextFieldCnpj.getText().replace(" ", "").replace(".", "").replace("/", "").replace("-", "");
        String telefone = jTextFieldTelefone.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");
        String cep = jTextFieldCep.getText().replace(" ", "").replace("(", "").replace(")", "").replace("-", "");

        if (jTextFieldBairro.getText().equals("")) {
            retorno = false;
            jLabelBairro.setForeground(Color.red);
        }
        if (jTextFieldCelular.getText().equals("(  )       -    ") || celular.length() < 11
                || celular.equals("00000000000") || celular.equals("22222222222") || celular.equals("33333333333")
                || celular.equals("44444444444") || celular.equals("55555555555") || celular.equals("66666666666")
                || celular.equals("77777777777") || celular.equals("88888888888") || celular.equals("99999999999")) {
            retorno = false;
            jTextFieldCelular.setText("");
            jLabelCelular.setForeground(Color.red);
        }
        if (jTextFieldCep.getText().equals("     -   ") || cep.length() < 8
                || cep.equals("00000000") || cep.equals("22222222") || cep.equals("33333333")
                || cep.equals("44444444") || cep.equals("55555555") || cep.equals("66666666")
                || cep.equals("77777777") || cep.equals("88888888") || cep.equals("99999999")) {
            retorno = false;
            jTextFieldCep.setText("");
            jLabelCep.setForeground(Color.red);
        }
        if (jTextFieldResponsavel.getText().equals("")) {
            retorno = false;
            jLabelResponsavel.setForeground(Color.red);
        }
        if (jTextFieldEmail.getText().equals("")) {
            retorno = false;
            jLabelEmail.setForeground(Color.red);
        }
        if (jTextFieldEndereco.getText().equals("")) {
            retorno = false;
            jLabelEndereco.setForeground(Color.red);
        }
        if (jTextFieldRazaoSocial.getText().equals("")) {
            retorno = false;
            jLabelRazaoSocial.setForeground(Color.red);
        }
        if (jTextFieldNumero.getText().equals("")) {
            retorno = false;
            jLabelNumero.setForeground(Color.red);
        }
        if (jTextFieldTelefone.getText().equals("(  )     -    ") || telefone.length() < 10
                || telefone.equals("0000000000") || telefone.equals("2222222222") || telefone.equals("3333333333")
                || telefone.equals("4444444444") || telefone.equals("5555555555") || telefone.equals("6666666666")
                || telefone.equals("7777777777") || telefone.equals("8888888888") || telefone.equals("9999999999")) {
            retorno = false;
            jTextFieldTelefone.setText("");
            jLabelTelefone.setForeground(Color.red);
        }
        if (ValidaCPFCNPJ.isValidCNPJ(cnpj)) {
            jLabelCnpj.setForeground(Color.BLACK);
        } else {
            jLabelCnpj.setForeground(Color.red);
            jTextFieldCnpj.setText("");
        }
        if (jComboBoxEstado.getSelectedIndex() == 0) {
            retorno = false;
            jLabelEstado.setForeground(Color.red);
        }
        if (jComboBoxCidade.getSelectedIndex() == 0) {
            retorno = false;
            jLabelCidade.setForeground(Color.red);
        }
        if (jComboBoxPais.getSelectedIndex() == 0) {
            retorno = false;
            jLabelPias.setForeground(Color.red);
        }
        if (retorno == false) {
            JOptionPane.showMessageDialog(null, "Existe campos obrigatorios em branco");
        }
        return retorno;
    }

    private void eventFocus() {
        jTextFieldCnpj.requestFocus();
        ArrayList<Component> order = new ArrayList<>();
        order.add(jTextFieldCnpj);
        order.add(jTextFieldRazaoSocial);
        order.add(jTextFieldResponsavel);
        order.add(jTextFieldEmail);
        order.add(jTextFieldCelular);
        order.add(jTextFieldTelefone);
        order.add(jTextFieldCep);
        order.add(jComboBoxPais);
        order.add(jComboBoxEstado);
        order.add(jComboBoxCidade);
        order.add(jTextFieldBairro);
        order.add(jTextFieldEndereco);
        order.add(jTextFieldNumero);
        order.add(jTextFieldComplemento);

        order.add(jButtonSalvar);
        order.add(jButtonCancelar);

        FocusLost focus = new FocusLost(order);
        setFocusTraversalPolicy(focus);
    }

    public void buscaCep() {
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jTextFieldCep.getText());

        if (webServiceCep.wasSuccessful()) {
            jComboBoxCidade.setEnabled(true);
            jComboBoxEstado.setEnabled(true);
            String pais = estadoDao.buscarPais(webServiceCep.getUf());
            String nomePais = paisDao.buscarPais(pais);
            jComboBoxPais.setSelectedItem(nomePais);
            preencherComboEstado();
            jComboBoxEstado.setSelectedItem(estadoDao.buscarEstado(webServiceCep.getUf()));
            preencherComboCidade();
            jComboBoxCidade.setSelectedItem(webServiceCep.getCidade());
            jTextFieldEndereco.setText(webServiceCep.getLogradouroFull());
            jTextFieldBairro.setText(webServiceCep.getBairro());

        } else {
            JOptionPane.showMessageDialog(null, "Cep Não Encontrado \n" + jTextFieldCep.getText());
            jLabelCep.setForeground(Color.red);
            jTextFieldCep.setText("");
        }
    }
}
