/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wss.viwer;

import br.com.wss.tabelas.TabelaUsuario;
import br.com.wss.tabelas.Tabela;
import br.com.wss.utilidades.ClassUtils;
import br.com.wss.dao.*;
import br.com.wss.modelo.*;
import br.com.wss.utilidades.ClassEvents;
import br.com.wss.utilidades.FocusLost;
import br.com.wss.utilidades.NumeroMaximoCaracters;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author WILLIAM
 */
public final class FrmUsuario extends javax.swing.JInternalFrame {

    ArrayList<Usuario> dados;
    String usuario = "";
    String usuarioSenha = "";
    String ativo = "";
    String logado = "";
    String idUsuario = "";
    int modificador = 1;

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        init();
        preencherTabela();
        eventFocus();
        jBExcluir.setEnabled(false);
        jPUsuario.setVisible(false);
        jPanelSenha.setVisible(false);
        jPopuMenuAtivar.setEnabled(false);
        jPopuMenuBloquear.setEnabled(false);
        jPopuMenuLibertar.setEnabled(false);
        jTextFieldNome.setDocument(new NumeroMaximoCaracters(30));
        jTextFieldUsuario.setDocument(new NumeroMaximoCaracters(20));

    }

    private void init() {
        initComponents();
        jTId.setVisible(false);
    }

    private void intensSelecionado() {
        int seleciona = jTabelaUsuario.getSelectedRow();
        jTId.setText(String.valueOf(dados.get(seleciona).getCodigo()));
        jTextFieldNome.setText(dados.get(seleciona).getNome());
        jTextFieldUsuario.setText(dados.get(seleciona).getUsuario());
        jPasswordFieldSenha.setText(dados.get(seleciona).getSenha());
        jPasswordFieldConfirmeSenha.setText(dados.get(seleciona).getSenha());
        modificadorCampos();
        modificador = 2;
    }

    private void itensPopuMenu() {
        int seleciona = jTabelaUsuario.getSelectedRow();

        if (seleciona != -1) {
            ativo = String.valueOf(dados.get(seleciona).getAtivo());
            logado = String.valueOf(dados.get(seleciona).getLogado());
            idUsuario = String.valueOf(dados.get(seleciona).getCodigo());

            if (ativo.equals("Sim")) {
                jPopuMenuAtivar.setEnabled(false);
                jPopuMenuBloquear.setEnabled(true);
            } else {
                jPopuMenuAtivar.setEnabled(true);
                jPopuMenuBloquear.setEnabled(false);
            }
            if (logado.equals("")) {
                jPopuMenuLibertar.setEnabled(false);
            } else {
                jPopuMenuLibertar.setEnabled(true);
            }
            modificadorCampos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rBStatus = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopuMenuAtivar = new javax.swing.JMenuItem();
        jPopuMenuBloquear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jPopuMenuLibertar = new javax.swing.JMenuItem();
        jPUsuario = new javax.swing.JPanel();
        jLNome = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonDefinirSenha = new javax.swing.JButton();
        jTId = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaUsuario = new javax.swing.JTable();
        jPanelSenha = new javax.swing.JPanel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jLabelConfirmeSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmeSenha = new javax.swing.JPasswordField();
        jButtonSalvarSenha = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jPopuMenuAtivar.setText("Ativar");
        jPopuMenuAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPopuMenuAtivarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jPopuMenuAtivar);

        jPopuMenuBloquear.setText("Desativar");
        jPopuMenuBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPopuMenuBloquearActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jPopuMenuBloquear);
        jPopupMenu1.add(jSeparator1);

        jPopuMenuLibertar.setText("Libertar");
        jPopuMenuLibertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPopuMenuLibertarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jPopuMenuLibertar);

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Usúario");

        jPUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuário"));
        jPUsuario.setLayout(null);

        jLNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNome.setText("Nome:");
        jPUsuario.add(jLNome);
        jLNome.setBounds(19, 30, 110, 20);

        jLUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLUsuario.setText("Usuário:");
        jPUsuario.add(jLUsuario);
        jLUsuario.setBounds(19, 60, 110, 20);

        jButtonSalvar.setText("variavel");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });
        jPUsuario.add(jButtonSalvar);
        jButtonSalvar.setBounds(140, 100, 80, 26);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPUsuario.add(jBCancelar);
        jBCancelar.setBounds(250, 100, 80, 26);

        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });
        jPUsuario.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(144, 60, 190, 26);

        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyPressed(evt);
            }
        });
        jPUsuario.add(jTextFieldNome);
        jTextFieldNome.setBounds(144, 30, 190, 26);

        jButtonDefinirSenha.setText("Definir Senha");
        jButtonDefinirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefinirSenhaActionPerformed(evt);
            }
        });
        jPUsuario.add(jButtonDefinirSenha);
        jButtonDefinirSenha.setBounds(10, 100, 110, 26);

        jTId.setEditable(false);
        jTId.setText("iD");
        jPUsuario.add(jTId);
        jTId.setBounds(196, 138, 26, 20);

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jTabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOME", "LOGIN"
            }
        ));
        jTabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaUsuarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelaUsuarioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaUsuario);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Senha"));
        jPanelSenha.setLayout(null);

        jPasswordFieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldSenhaFocusLost(evt);
            }
        });
        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        jPanelSenha.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(144, 30, 190, 26);

        jLabelSenha.setText("Senha:");
        jPanelSenha.add(jLabelSenha);
        jLabelSenha.setBounds(19, 30, 110, 20);

        jLabelConfirmeSenha.setText("Confirme Senha:");
        jPanelSenha.add(jLabelConfirmeSenha);
        jLabelConfirmeSenha.setBounds(19, 60, 110, 20);

        jPasswordFieldConfirmeSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldConfirmeSenhaFocusLost(evt);
            }
        });
        jPasswordFieldConfirmeSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldConfirmeSenhaKeyPressed(evt);
            }
        });
        jPanelSenha.add(jPasswordFieldConfirmeSenha);
        jPasswordFieldConfirmeSenha.setBounds(144, 60, 190, 26);

        jButtonSalvarSenha.setText("Salvar");
        jButtonSalvarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarSenhaActionPerformed(evt);
            }
        });
        jButtonSalvarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarSenhaKeyPressed(evt);
            }
        });
        jPanelSenha.add(jButtonSalvarSenha);
        jButtonSalvarSenha.setBounds(140, 110, 80, 26);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelSenha.add(jButtonCancelar);
        jButtonCancelar.setBounds(260, 110, 80, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBNovo)
                        .addGap(49, 49, 49)
                        .addComponent(jBExcluir)))
                .addGap(72, 424, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBNovo)
                    .addComponent(jBExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setBounds(0, 0, 1139, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (modificador == 1) {
            jButtonSalvar.setText("Salvar");
            cadastrar();
        } else if (modificador == 2) {
            jButtonSalvar.setText("Editar");
            atualizar();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Usuario usuarioTemp = new Usuario();
        usuarioTemp.setUsuario(jTextFieldUsuario.getText());
        UsuarioDao dao = new UsuarioDao();
        if (dao.deletar(usuarioTemp)) {

            jPUsuario.setVisible(false);
            jBNovo.setEnabled(true);
            jBExcluir.setEnabled(false);
            preencherTabela();
            limparCanpos();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        if (modificador == 1) {
            jPUsuario.setVisible(true);
            jBNovo.setEnabled(false);
            jBExcluir.setEnabled(false);
            jBExcluir.setVisible(true);
            jButtonSalvar.setVisible(true);
            jButtonSalvar.setEnabled(true);
            limparCanpos();
            jButtonSalvar.setText("Salvar");
        } else {
            modificador = 1;
            jPUsuario.setVisible(true);
            jBNovo.setEnabled(false);
            jBExcluir.setEnabled(false);
            jBExcluir.setVisible(true);
            jButtonSalvar.setVisible(true);
            jButtonSalvar.setEnabled(true);
            limparCanpos();
            jButtonSalvar.setText("Salvar");
        }
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jPUsuario.setVisible(false);
        jPanelSenha.setVisible(false);
        jBNovo.setEnabled(true);
        jBExcluir.setEnabled(false);
        limparCanpos();
        modificador = 1;
        modificadorCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaUsuarioMouseClicked

        if (evt.getClickCount() == 2) {
            intensSelecionado();
            jPUsuario.setVisible(true);
            jPanelSenha.setVisible(false);
            jBNovo.setEnabled(false);
            jBExcluir.setEnabled(true);
            jBExcluir.setVisible(true);
            modificador = 2;
            jButtonSalvar.setText("Editar");
            jLNome.setForeground(Color.black);
            jLUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTabelaUsuarioMouseClicked

    private void jButtonDefinirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefinirSenhaActionPerformed
        jPanelSenha.setVisible(true);
        jPUsuario.setVisible(true);
    }//GEN-LAST:event_jButtonDefinirSenhaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jPanelSenha.setVisible(false);
        jPUsuario.setEnabled(true);
        jPasswordFieldConfirmeSenha.setText("");
        jPasswordFieldSenha.setText("");
        jPUsuario.setVisible(true);
        jLabelSenha.setForeground(Color.BLACK);
        jLabelConfirmeSenha.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarSenhaActionPerformed
        if (!new String(jPasswordFieldSenha.getPassword()).equals("")
                && !new String(jPasswordFieldConfirmeSenha.getPassword()).equals("")
                && new String(jPasswordFieldSenha.getPassword()).equals(new String(jPasswordFieldConfirmeSenha.getPassword()))) {
            jPanelSenha.setVisible(false);
            jPUsuario.setEnabled(true);
            jLabelSenha.setForeground(Color.BLACK);
            jLabelConfirmeSenha.setForeground(Color.BLACK);
            jPUsuario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "As Senhas Não são Iguais");
            jLabelSenha.setForeground(Color.red);
            jLabelConfirmeSenha.setForeground(Color.red);
            jPUsuario.setVisible(true);
            jPanelSenha.setVisible(true);
            jPasswordFieldSenha.requestFocus();
        }
    }//GEN-LAST:event_jButtonSalvarSenhaActionPerformed

    private void jTextFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jTextFieldNome.getText().equals("")) {
            jTextFieldUsuario.requestFocus();
            jLNome.setForeground(Color.BLACK);
        } else {
            jLNome.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldNomeKeyPressed

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jTextFieldUsuario.getText().equals("")) {

            if (!jPasswordFieldConfirmeSenha.getPassword().equals("") && !jPasswordFieldSenha.getPassword().equals("")) {
                jPanelSenha.setVisible(false);
                jButtonSalvar.requestFocus();
                jPasswordFieldSenha.requestFocus();
            } else {
                jPanelSenha.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jPasswordFieldSenha.getPassword().equals("")) {
            jPasswordFieldConfirmeSenha.requestFocus();
            jLabelSenha.setForeground(Color.BLACK);
        } else {
            jLabelSenha.setForeground(Color.red);
        }
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    private void jPasswordFieldConfirmeSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmeSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jPasswordFieldConfirmeSenha.getPassword().equals("")) {
            jButtonSalvarSenha.requestFocus();
            jLabelConfirmeSenha.setForeground(Color.BLACK);
        } else {
            jLabelConfirmeSenha.setForeground(Color.red);
        }
    }//GEN-LAST:event_jPasswordFieldConfirmeSenhaKeyPressed

    private void jButtonSalvarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarSenhaKeyPressed
        if (!new String(jPasswordFieldSenha.getPassword()).equals("")
                && !new String(jPasswordFieldConfirmeSenha.getPassword()).equals("")
                && new String(jPasswordFieldSenha.getPassword()).equals(new String(jPasswordFieldConfirmeSenha.getPassword()))) {
            jPanelSenha.setVisible(false);
            jPUsuario.setEnabled(true);
            jLabelSenha.setForeground(Color.BLACK);
            jLabelConfirmeSenha.setForeground(Color.BLACK);
            jPUsuario.setVisible(true);
            jButtonSalvar.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "As Senhas Não são Iguais");
            jLabelSenha.setForeground(Color.red);
            jLabelConfirmeSenha.setForeground(Color.red);
            jPUsuario.setVisible(true);
            jPanelSenha.setVisible(true);
            jPasswordFieldSenha.requestFocus();
        }
    }//GEN-LAST:event_jButtonSalvarSenhaKeyPressed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        if (modificador == 1) {
            jButtonSalvar.setText("Salvar");
            cadastrar();
        } else if (modificador == 2) {
            jButtonSalvar.setText("Editar");
            atualizar();
        }
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jTabelaUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaUsuarioMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
            itensPopuMenu();
        }
    }//GEN-LAST:event_jTabelaUsuarioMouseReleased

    private void jPopuMenuAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPopuMenuAtivarActionPerformed
        ativarUsuario();
    }//GEN-LAST:event_jPopuMenuAtivarActionPerformed

    private void jPopuMenuBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPopuMenuBloquearActionPerformed
        desativarUsuario();
    }//GEN-LAST:event_jPopuMenuBloquearActionPerformed

    private void jPopuMenuLibertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPopuMenuLibertarActionPerformed
        libertaUsuario();
    }//GEN-LAST:event_jPopuMenuLibertarActionPerformed

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        ClassEvents.focusLostTextField(jLNome, jTextFieldNome);
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        ClassEvents.focusLostTextField(jLUsuario, jTextFieldUsuario);
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordFieldSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaFocusLost
        ClassEvents.focusLostTextField(jLabelSenha, jPasswordFieldSenha);
    }//GEN-LAST:event_jPasswordFieldSenhaFocusLost

    private void jPasswordFieldConfirmeSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmeSenhaFocusLost
        ClassEvents.focusLostTextField(jLabelConfirmeSenha, jPasswordFieldConfirmeSenha);
    }//GEN-LAST:event_jPasswordFieldConfirmeSenhaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDefinirSenha;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSalvarSenha;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabelConfirmeSenha;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPUsuario;
    private javax.swing.JPanel jPanelSenha;
    private javax.swing.JPasswordField jPasswordFieldConfirmeSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JMenuItem jPopuMenuAtivar;
    private javax.swing.JMenuItem jPopuMenuBloquear;
    private javax.swing.JMenuItem jPopuMenuLibertar;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTId;
    private javax.swing.JTable jTabelaUsuario;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.ButtonGroup rBStatus;
    // End of variables declaration//GEN-END:variables

    private void limparCanpos() {
        jTextFieldNome.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldConfirmeSenha.setText("");
        jPasswordFieldSenha.setText("");
        jTId.setText("");
    }

    private void atualizar() {
        Usuario usuarioTemp = new Usuario();

        usuarioTemp.setNome(jTextFieldNome.getText());
        usuarioTemp.setUsuario(jTextFieldUsuario.getText());
        usuarioTemp.setSenha(new String(jPasswordFieldSenha.getPassword()));
        usuarioTemp.setCodigo(jTId.getText());
        usuarioTemp.setIdUsuarioAlt((ClassUtils.getIdUsuario()));
        usuarioTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());

        UsuarioDao dao = new UsuarioDao();
        if (dao.atualizar(usuarioTemp)) {
            limparCanpos();
            preencherTabela();
            modificadorCampos();

            jPUsuario.setVisible(false);
            jPanelSenha.setVisible(false);
            jBNovo.setVisible(true);
            jBNovo.setEnabled(true);
            jBExcluir.setVisible(true);
            jBExcluir.setEnabled(false);
            jButtonSalvar.setVisible(true);
            limparCanpos();

        }
    }

    private void ativarUsuario() {
        if (!idUsuario.equals("") && !ativo.equals("")) {
            Usuario usuarioTemp = new Usuario();
            usuarioTemp.setCodigo(idUsuario);
            usuarioTemp.setAtivo("Sim");
            usuarioTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
            usuarioTemp.setIdUsuarioAlt(ClassUtils.getIdUsuario());

            UsuarioDao dao = new UsuarioDao();
            if (dao.ativarUsuario(usuarioTemp)) {
                jPopuMenuAtivar.setEnabled(false);
                preencherTabela();
            }
        }
    }

    private void libertaUsuario() {
        if (!logado.equals("")) {
            Usuario usuarioTemp = new Usuario();
            usuarioTemp.setLogado("");
            usuarioTemp.setCodigo(idUsuario);
            UsuarioDao dao = new UsuarioDao();
            if (dao.libertar(usuarioTemp)) {
                jPopuMenuLibertar.setEnabled(false);
                preencherTabela();
            }
        }
    }

    private void desativarUsuario() {
        if (!idUsuario.equals("") && !ativo.equals("")) {
            Usuario usuarioTemp = new Usuario();
            usuarioTemp.setCodigo(idUsuario);
            usuarioTemp.setAtivo("Não");
            usuarioTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
            usuarioTemp.setIdUsuarioAlt(ClassUtils.getIdUsuario());

            UsuarioDao dao = new UsuarioDao();
            if (dao.ativarUsuario(usuarioTemp)) {
                jPopuMenuBloquear.setEnabled(false);
                preencherTabela();
            }
        }
    }

    private void cadastrar() {
        if (valida()) {
            if (!new String(jPasswordFieldSenha.getPassword()).equals("") && !new String(jPasswordFieldConfirmeSenha.getPassword()).equals("")) {

                Usuario usuarioTemp = new Usuario();
                usuarioTemp.setNome(jTextFieldNome.getText());
                usuarioTemp.setUsuario(jTextFieldUsuario.getText());
                usuarioTemp.setUltimaAlteracao(ClassUtils.setDateMsqy());
                usuarioTemp.setDataCadastro(ClassUtils.setDateMsqy());
                usuarioTemp.setSenha(new String(jPasswordFieldSenha.getPassword()));
                usuarioTemp.setIdUsuarioCad((ClassUtils.getIdUsuario()));
                usuarioTemp.setIdUsuarioAlt(ClassUtils.getIdUsuario());
                usuarioTemp.setLogado("");
                usuarioTemp.setAtivo("Sim");

                UsuarioDao dao = new UsuarioDao();

                if (dao.cadastrarUsuario(usuarioTemp)) {
                    limparCanpos();
                    jPUsuario.setVisible(false);
                    jPanelSenha.setVisible(false);
                    jBNovo.setEnabled(true);
                    jBExcluir.setEnabled(false);
                    preencherTabela();
                    modificadorCampos();
                } else {
                    jTextFieldNome.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Necessario Cadastrar Uma Senha!");
                jPUsuario.setVisible(true);
                jPanelSenha.setVisible(true);
                jPasswordFieldSenha.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhun campo pode ser vazio!");
            jTextFieldUsuario.requestFocus();
            jLUsuario.setBackground(Color.red);
        }
    }

    private void preencherTabela() {

        String[] Colunas = new String[]{"  ","Nome", "Usuário", "Logado Em", "Ativo", "Data Castro", "Ultima Alteração"};

        UsuarioDao usuarioDao = new UsuarioDao();
        dados = usuarioDao.listar();
        Tabela modelo = new TabelaUsuario(dados, Colunas);
        jTabelaUsuario.setModel(modelo);

        jTabelaUsuario.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTabelaUsuario.getColumnModel().getColumn(0).setResizable(false);
        
        jTabelaUsuario.getColumnModel().getColumn(1).setPreferredWidth(210);
        jTabelaUsuario.getColumnModel().getColumn(1).setResizable(false);

        jTabelaUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTabelaUsuario.getColumnModel().getColumn(2).setResizable(false);

        jTabelaUsuario.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTabelaUsuario.getColumnModel().getColumn(3).setResizable(false);

        jTabelaUsuario.getColumnModel().getColumn(4).setPreferredWidth(55);
        jTabelaUsuario.getColumnModel().getColumn(4).setResizable(false);

        jTabelaUsuario.getColumnModel().getColumn(5).setPreferredWidth(325);
        jTabelaUsuario.getColumnModel().getColumn(5).setResizable(false);

        jTabelaUsuario.getColumnModel().getColumn(6).setPreferredWidth(325);
        jTabelaUsuario.getColumnModel().getColumn(6).setResizable(false);

        jTabelaUsuario.getTableHeader().setReorderingAllowed(false);
        jTabelaUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTabelaUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    private boolean valida() {
        boolean retorno = true;
        if (jTextFieldNome.getText().equals("")) {
            retorno = false;
            jLNome.setForeground(Color.red);
        }
        if (jTextFieldUsuario.getText().equals("")) {
            retorno = false;
            jLUsuario.setForeground(Color.red);
        }
        if (jPasswordFieldConfirmeSenha.getPassword().equals("")) {
            retorno = false;
            jLabelConfirmeSenha.setForeground(Color.red);
        }
        if (jPasswordFieldSenha.getPassword().equals("")) {
            retorno = false;
            jLabelSenha.setForeground(Color.red);
        }if (retorno == false) {
            JOptionPane.showMessageDialog(null, "Existe campos obrigatorios em branco");
        }
        return retorno;
    }

    private void eventFocus() {

        ArrayList<Component> order = new ArrayList<>();
        order.add(jTextFieldNome);
        order.add(jTextFieldUsuario);
        order.add(jButtonSalvar);
        order.add(jPasswordFieldSenha);
        order.add(jPasswordFieldConfirmeSenha);
        order.add(jButtonSalvarSenha);
        order.add(jButtonCancelar);
        order.add(jButtonSalvar);
        order.add(jBCancelar);

        FocusLost focus = new FocusLost(order);
        setFocusTraversalPolicy(focus);
    }

    private void modificadorCampos() {
        jLabelConfirmeSenha.setForeground(Color.BLACK);
        jLabelSenha.setForeground(Color.BLACK);
        jLNome.setForeground(Color.BLACK);
        jLUsuario.setForeground(Color.BLACK);
    }
}
